all: qsort qsort_stdlib bubblesort insertion_sort

qsort: qsort.c
	gcc -Wall -o $@ $<

qsort_stdlib: qsort_stdlib.c
	gcc -Wall -o $@ $<

bubblesort: bubblesort.c
	gcc -Wall -o $@ $<

insertion_sort: insertion_sort.c
	gcc -Wall -o $@ $<

