# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/28-cloud-base"
  config.vm.define "recodex-measurements"

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    dnf -y copr enable semai/ReCodEx
    dnf -y install --refresh isolate
    dnf -y install perf stress-ng
  SHELL
end
