# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if ARGV[0] == "up" and ENV["MEASUREMENTS_ROOT"].nil? then
    raise Vagrant::Errors::VagrantError.new, "MEASUREMENTS_ROOT env var not set"
  end

  (0..39).each do |i|
    config.vm.define "vbox_#{i}" do |vbox|
      vbox.vm.box = "recodex-measurements-template"
      vbox.vm.box_url = "file://#{ENV["MEASUREMENTS_ROOT"]}/vagrant/template.box"

      vbox.vm.synced_folder '.', '/vagrant', disabled: true
      vbox.vm.synced_folder ENV["MEASUREMENTS_ROOT"], "/measurements", type: "rsync", rsync__auto: true, rsync__exclude: ["#{ENV["MEASUEREMENTS_ROOT"]}/vagrant", "#{ENV["MEASUEREMENTS_ROOT"]}/docker", "#{ENV["MEASUEREMENTS_ROOT"]}/results*"]

      vbox.vm.network :forwarded_port, id: "ssh", guest: 22, host: (9000 + i)
      vbox.ssh.guest_port = (9000 + i)

      vbox.vm.provision "shell", inline: <<-SHELL
        cd /measurements
      SHELL
    end
  end
end
