# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if ARGV[0] == "up" and ENV["MEASUREMENTS_ROOT"].nil? then
    raise Vagrant::Errors::VagrantError.new, "MEASUREMENTS_ROOT env var not set"
  end

  for i in 0..39
    config.vm.define "vbox_#{i}" do |vbox|
      vbox.vm.box = "recodex-measurements-template"
      vbox.vm.box_url = "file://#{ENV["MEASUREMENTS_ROOT"]}/runners/package.box"

      vbox.vm.synced_folder '.', '/vagrant', disabled: true
      vbox.vm.synced_folder ENV["MEASUREMENTS_ROOT"], "/measurements", type: "rsync"

      vbox.vm.network :forwarded_port, guest: 22, host: (2222 + i)

      vbox.vm.provision "shell", inline: <<-SHELL
        cd /measurements
      SHELL
    end
  end
end
